### ISSUE TITLE
Unknown Crash

### ISSUE THREAD

**Issue by Goktug** [sbertix/ComposableRequest#12]
Hi @sbertix,

I am using `ComposableRequest` version `4.0.5` in my project.  Sometimes, app crashes in this line. However, there is no crash or error info in the terminal.  Only, I have taken these screenshots. I hope this can be helpful. Do you know any idea why is happening?

**Stacktrace**
<img width="1680" alt="2" src="https://user-images.githubusercontent.com/534426/91552680-dd624e80-e934-11ea-9b28-6a3d8279d423.png">
<img width="1680" alt="3" src="https://user-images.githubusercontent.com/534426/91552699-e2bf9900-e934-11ea-839f-8e1b5e06f5dd.png">

**Comment by sbertix** [comment]
Hey @Goktug.\
Are you using this with `Realm`, `CoreData` or some other non-thread safe implementations?\
Cause that tends to be the issue most times something like this occurs, as the response is not delivered in the same thread of the request.

```swift
let realm = try? Realm()
Endpoint.Something.something
   .task { _ in realm.something }   // this crashes silently like above.
   .resume()
```

**Comment by Goktug** [comment]
Hey @sbertix,

Yes, I am using `Realm` however in my opinion, this isn't the case. I am also using RxSwift for the sake of reactivity and every time I need to access a realm object, I switch the thread I wanted with using `.observeOn(ConcurrentDispatchQueueScheduler.workingQueue())`

**Comment by sbertix** [comment]
We saw it happening with @anonrig and it really tends to be because of that.\
Are you maybe retaining a `Realm` `Object` somewhere instead of referring to it's `primaryKey` for instance?\
Are you perhaps using the same `Realm` inside `.task { }`, instead of instantiating a new one?\
Thread safety in `Realm` comes down to more than just observing on a fix scheduler, unfortunately.

**Comment by sbertix** [comment]
I'm closing this as it's not related to **ComposableRequest** per se, but to a specific implementation.\
Let's keep the conversation going though, as I'm more than happy to help you out, if you need it to figure out where the mistake is.

**Comment by Goktug** [comment]
Okay @sbertix Thank you for your help. I found some memory leaks and fixed them. I am going to observe for a while.

**Comment by Goktug** [comment]
Hey @sbertix, It happened again and this time I am not using realm models. 

<img width="1674" alt="Screen Shot 2020-09-02 at 17 32 54" src="https://user-images.githubusercontent.com/534426/91997103-6537c680-ed42-11ea-8582-2723789a94e0.png">

**Comment by sbertix** [comment]
Next week I'm gonna start working a new and improved dispatch system for `Requester.Task`s, hoping I can reduce incompatibilities with thread safe implementations, such as these errors 💪

**Comment by Goktug** [comment]
Thank you @sbertix, I am going to postpone my release date. I am looking forward to hearing an update from you.
