### ISSUE TITLE
WebViewAuthenticator  EXC_BAD_ACCESS error before version 13

### ISSUE THREAD

**Issue by aslios** [sbertix/ComposableRequest#13]
When I run WebViewAuthenticator with less version than ios 13 (ios 12)  it gives  EXC_BAD_ACCESS error i cannot open instagram 
 login page :/ 
How can i fix this?
Thank you

**Comment by sbertix** [comment]
Hey @aslios, I've fixed the crash in **ComposableRequest** `4.3.1`. 
I'm pushing an update to [**Swiftagram**](https://github.com/sbertix/Swiftagram) asap to reflect the changes. 
Let me know if it works for you too.

**Comment by aslios** [comment]
thank you sbertix 👍 :)
