### ISSUE TITLE
KeychainStorage doesn't work in release mode properly

### ISSUE THREAD

**Issue by Goktug** [sbertix/ComposableRequest#15]
- [X] I've searched past issues and I couldn't find reference to this. 

**Swiftagram version**
`4.1.3`

**Describe the bug**
New KeychainStorage couldn't retrieve the data from Keychain in Release mode. If I try to do the same thing in Debug mode, it works.

**To reproduce**
1. Login with Instagram
2. Kill the app after login successfully 
3. Open the app again
4. `KeychainStorage<Secret>(service: Constant.Identifier.keychainStorage).all().first` code will return empty data

**Expected behavior**
I expected to retrieve last stored Secret object using this code `KeychainStorage<Secret>(service: Constant.Identifier.keychainStorage).all().first` 

**Additional Context**
WebViewAuthenticator initialized with `KeychainStorage<Secret>(service: Constant.Identifier.keychainStorage)` as well.

```
    WebViewAuthenticator(storage: KeychainStorage<Secret>(service: Constant.Identifier.keychainStorage)) { self.webView = $0 }
      .authenticate { [weak self] in
        // do stuff
      }
```

**Device and system**
iPhone XS Max - iOS 14.0

**IDE**
XCode 12.0.1

**Comment by sbertix** [comment]
Hey @Goktug,
I've pushed an update for **Swifthcain** that I think might cause this. 
Do you mind updating your SPM dependencies and letting me know if it still fails with **Swiftchain** `1.0.1`?

**Comment by Goktug** [comment]
Hey @sbertix 

Thank you for your quick response. Unfortunately, I am having the same issue with the new version too.

**Comment by sbertix** [comment]
Do you mind editing `KeychainStorage.swift` row 64 in **ComposableRequestCrypto**, and replace it with…

```swift
        do {
            return try keychain.containers().compactMap { try $0.fetch(Data.self).flatMap { try? JSONDecoder().decode(Secret.self, from: $0) } }
        } catch {
            fatalError(error.localizedDescription)
        }
```

If it fails, do you mind pasting the `fatalError` `message` here, please? Thank you 💪

**Comment by Goktug** [comment]
Sure, this is the error:

`Thread 1: Fatal error: A required entitlement isn't present.`

**Comment by sbertix** [comment]
I've fixed the entitlement issues, and everything seems to work in my tests. 
I've just pushed **Swiftchain** `1.0.3`. Let me know if by updating your SPM dependencies it works, or if it still turns out empty, cause in that case there might an issue in your codebase.

**Comment by sbertix** [comment]
I'm closing this issue as all remaining issues are related to @Goktug's own code, as we figured out privately.
