### ISSUE TITLE
Delay in 5.3 is not working

### ISSUE THREAD

**Issue by VitaliiDeveloper** [sbertix/ComposableRequest#52]
**Swiftagram version**
v 5.4.0

**Describe the bug**
When you will try to set a delay for followers/following requests it gonna be ignored.

**To reproduce**
1. Make a request on followers/following

```
Endpoint.user(secret.identifier)
                .following
                .unlock(with: secret)
                .session(.instagram)
                .pages(.max, delay: 5)
```

2. Check for example the Charles for time URLs hires (each new request gonna be ignore the delays and will hire immediately)

**Expected behavior**
Each new request for following/follers gonna be hire after the delay

**Device and system**
iPhone Simulator 16.2

**Comment by sbertix** [comment]
Hey @VitaliiDeveloper, 
Thank you for pointing this out. I'm not really sure how it escaped everyone, including me, for this long 😱 

I've released a bug fix to version `5.3.*` of [**ComposableRequest**](https://github.com/sbertix/ComposableRequest), used by [**Swiftagram**](https://github.com/sbertix/Swiftagram) on `main` and on its latest releases, so you can have it immediately working by just updating your packages to the latest versions in Xcode and making sure **ComposableRequest** says `5.3.2` afterwards.
